"""empty message

Revision ID: 0c86238423fb
Revises: ac8c084ad297
Create Date: 2021-04-11 08:18:20.948617

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0c86238423fb'
down_revision = 'ac8c084ad297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'name')
    # ### end Alembic commands ###
