"""empty message

Revision ID: 24fb3b504008
Revises: c41ff70698dd
Create Date: 2021-05-26 21:03:51.925904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24fb3b504008'
down_revision = 'c41ff70698dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('is_outline', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'is_outline')
    # ### end Alembic commands ###
