"""empty message

Revision ID: 51c7c9f7cc29
Revises: c00ccb1e7047
Create Date: 2021-04-17 14:40:48.831353

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '51c7c9f7cc29'
down_revision = 'c00ccb1e7047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('authenticated', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    op.drop_column('users', 'authenticated')
    # ### end Alembic commands ###
