"""empty message

Revision ID: 881f590b7c5f
Revises: 
Create Date: 2021-04-02 16:56:44.357657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881f590b7c5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
