"""empty message

Revision ID: a403585c54e6
Revises: 635b20d0bd65
Create Date: 2021-04-29 17:23:00.740370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a403585c54e6'
down_revision = '635b20d0bd65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('starting_image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'images', 'images', ['starting_image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'starting_image_id')
    # ### end Alembic commands ###
