"""empty message

Revision ID: c00ccb1e7047
Revises: f090bb003399
Create Date: 2021-04-17 14:22:09.321038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c00ccb1e7047'
down_revision = 'f090bb003399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('images', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'updated_on')
    op.drop_column('images', 'created_on')
    # ### end Alembic commands ###
