"""empty message

Revision ID: c41ff70698dd
Revises: 12a7502b0990
Create Date: 2021-05-11 17:21:30.315239

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c41ff70698dd'
down_revision = '12a7502b0990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'is_visible')
    # ### end Alembic commands ###
