"""empty message

Revision ID: f090bb003399
Revises: 0c86238423fb
Create Date: 2021-04-17 14:21:09.771061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f090bb003399'
down_revision = '0c86238423fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_on')
    op.drop_column('users', 'created_on')
    # ### end Alembic commands ###
